# Generated by Django 5.0.3 on 2024-05-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_page_sum_of_amounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
