# Generated by Django 5.0.3 on 2024-05-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_document_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('no_of_pages', models.IntegerField()),
                ('amounts', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='document',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
