# Generated by Django 5.0.3 on 2024-05-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_accounts_remove_page_document_delete_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='page_amounts',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='amounts',
            field=models.TextField(default='{}'),
        ),
    ]
