# Generated by Django 5.0.3 on 2024-05-31 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_accounts_page_amounts_alter_accounts_amounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='amounts',
        ),
    ]
