# Generated by Django 5.0.3 on 2024-05-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_accounts_amounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='page_amounts',
            field=models.TextField(default=''),
        ),
    ]
