# Generated by Django 5.0.3 on 2024-06-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_accounts_page_amounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobil', models.IntegerField(max_length=15)),
                ('comment', models.TextField(default='')),
            ],
        ),
    ]
