# Generated by Django 5.0.3 on 2024-06-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='mobil',
            field=models.CharField(max_length=15),
        ),
    ]
